### ISSUE TITLE
Symbols needs some sort of visual aid

### ISSUE THREAD

**Issue by imNel** [Joshuahuahua/KTANE-ASSISTANT#5]
Currently the descriptions for each symbol are not the best. Either a new method for this module needs to be found or some sort of visual aid needs to be provided.

**Comment by ioNelio** [comment]
Also to add to this, with a visual aid, a less descriptive word could be given to each symbol which would make for faster solving.

**Comment by Joshuahuahua** [comment]
Updated symbols.py
This change includes aliases for the symbols and a table of said symbols and their unicode equivalents
Will be released in the 1.1.0 update
